### ISSUE TITLE
Build a Concurrently Traversable Tree

### ISSUE THREAD

**Issue by RobbieMcKinstry** [alligrader/jobs#1]
We want to represent our job as a tree, where each node has a list of children.
We need to establish a `Job` as a series of `Tasks`, where each `Task`. See [the readme](https://github.com/alligrader/jobs/blob/master/README.md) for more information on why we want to use this representation. Each `Task` can have a variable number of `Tasks` that depend on it. This leads us to a tree-representation: our `Tasks` are themselves nodes, and each node has an array of children `Tasks`. The children `Tasks` won't be executed until its parent is executed, and it will be executed with a context provided by its parent. Each child, however, is independent of any of its siblings, so we're going to execute each sibling in its own thread (_i.e._ goroutine). Here are the types for the `Tree`, the `TreeNode`, and the contents of the `TreeNode` (which must fulfill the `Visitable` interface, which a `Task` will fulfill).

```
import "fmt"
import "context"
import "sync"

type Tree struct {
    Contents map[string] []*TreeNode
    Root *TreeNode
}

type TreeNode struct {
    contents Visitable
    children []string // the index into the Tree.Contents
    container *Tree        // a pointer to the Tree, so you can reach into the contents
}

type Visitable interface{
    Visit(context.Context) (context.Context, error)
}
```

We need to implement the `Walk` method for both the `Tree` and the `TreeNode` types. I provided most of the logic for these methods, but I need you to test and make sure they work. Additionally, we need to implement the `Tree.NewNode()` method so we can add nodes to the tree.

You should see [this link](https://golang.org/doc/play/tree.go) for some sample code. The sample code runs in two threads: one fo the walker, which reads from the channel, and the other that walks (visits) each node in pre-order. We want our tree-walker to be [in-order](https://en.wikipedia.org/wiki/Tree_traversal#Pre-order) instead of pre-order. 

Additionally, instead of only having two threads of execution like the example, we want to walk each TreeNode, visit its contents, and then spawn a thread for each of its children. This will dramatically decrease the amount of time it takes to traverse the tree (assuming it's a big tree, which in reality it isn't).

Below is the code I wrote for `Tree.Walk` and `TreeNode.Walk`. It's not guarenteed to compile, nor is it necessarily correct. It's definitely a good starting point.

```
func (tree *Tree) Walk() {
    var done sync.WaitGroup
    done.Add(1) // we have to visit the Root first.

    go func() {
       // make the parent context
       ctx := context.Background()
       if _, err := tree.Root.visitAllChildren(ctx, done); err != nil {
            log.Printlnl(err) // report the error
       }
       done.Done()
    }()

    done.Wait()
}

func (node *TreeNode) Walk(ctx context.Context, done sync.WaitGroup) {
     // tell your parent that you're done
    defer done.Done()

    // visit the contents
    childCtx, err := node.Contents.Visit(ctx)
    if err != nil {
        // if there was an error, report it
        log.Fatal(err)
    }

    // visit each child.
    node.visitAllChildren(childCtx)
}

func (node  *TreeNode) visitAllChildren(ctx context.Context, wg sync.WaitGroup) {
    wg.Add(len(node.children))
    for _, child := range node.children {
        go func() {
            node.container[child].Walk(ctx, wg)
        }()
    }
}
```

Finally, also implement the method 
```
func (tree *Tree) NewNode(name, parent string, contents Visitable)
```
This should look up the parent node in the tree and add this node to the list of children. It should look something like this:

```
// NewTree creates a new, empty tree.
func NewTree() *Tree {
    t := &Tree{}
    t.Root = &TreeNode{
        contents: nil,
        children: []stringr{},
        container: t,
    }
    t.Contents = map[string][]*TreeNode{
        "Root": t.Root,
    }

    return t
}

func (tree *Tree) NewNode(name string, parent string, contents Visitable) {
    if parent, ok := tree.Contents[parent]; !ok {
        panic("No such parent.")
    }
    newChild := &TreeNode{
        contents: contents,
        children: []string{},
        container: tree,
    }
    parent.children = append(parent.children, newChild)
}
```

Your job is implement the source using the above sample code, and to test it to make sure that it works. You should look at [the testing package](https://golang.org/pkg/testing/) to information on how to test, as well as [this tutorial](https://golang.org/doc/code.html#Testing).

**Comment by danieljustice** [comment]
closed by https://github.com/alligrader/jobs/pull/3
